name: 'Install dependencies'
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        tools/install-sys-dependencies-mac

    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v3
      with:
        path: build/local
        key: ${{ runner.os }}-${{ runner.arch }}-internal-${{ hashFiles('tools/install-dependencies') }}

    - name: Install internal dependencies
      shell: bash
      run: |
        tools/install-dependencies

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          rust

    - name: Install Rust dependencies
      shell: bash
      run: |
        tools/install-rust-dependencies
