ENV['COCOAPODS_DISABLE_STATS'] = 'true'

deployment_target = '12.0'
platform :ios, deployment_target
inhibit_all_warnings!

project 'TrustWalletCore.xcodeproj'

target 'WalletCore' do
  use_frameworks!

  # 1. The SwiftProtobuf library version must match the version specified in the `swift-protobuf-version.properties` file 
  #    (`version_tag` property in this file).
  # 2. Before upgrading, make sure that the new version of the SwiftProtobuf library is compatible with other consumers
  #    of the binary artifact (`grpc-swift`, `hedera-sdk-swift`, `SwiftBinanceChain`, `blockchain-sdk-swift` and so on).
  pod 'SwiftProtobuf', '=1.25.2'

  target 'WalletCoreTests'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # remove deployment_target from target level
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
