#!/bin/bash

get_property() {
    local property_file=$1
    local property_key=$2
    grep "^$property_key=" "$property_file" | cut -d'=' -f2
}

export GTEST_VERSION=1.11.0
export CHECK_VERSION=0.15.2
export JSON_VERSION=3.10.2
export PROTOBUF_VERSION=3.19.2
export SWIFT_PROTOBUF_VERSION=$(get_property "swift-protobuf-version.properties" "version_tag")
