#!/bin/bash

set -e

NIGHTLY="nightly-2024-03-17"  # Latest 1.78 nightly
STABLE="stable-2024-05-02"  # https://releases.rs/docs/1.78.0/

RUST_RELEASE=$NIGHTLY

rustup toolchain install $RUST_RELEASE
rustup default $RUST_RELEASE
rustup toolchain install $RUST_RELEASE-x86_64-apple-darwin --force-non-host
rustup toolchain install $RUST_RELEASE-aarch64-apple-darwin --force-non-host
rustup component add rust-src --toolchain $RUST_RELEASE-aarch64-apple-darwin
rustup component add rust-src --toolchain $RUST_RELEASE-x86_64-apple-darwin
if [[ `uname` == "Linux" ]]; then
  rustup component add rust-src --toolchain $RUST_RELEASE-x86_64-unknown-linux-gnu
fi

# Android
rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
# iOS
rustup target add aarch64-apple-darwin x86_64-apple-darwin
# macOS
rustup target add x86_64-apple-ios aarch64-apple-ios-sim aarch64-apple-ios
# Wasm
rustup target add wasm32-unknown-emscripten

cargo install cbindgen --locked

if [[ "$1" == "dev" ]]; then
  rustup component add llvm-tools-preview clippy rustfmt
  cargo install cargo-llvm-cov --locked
fi
