#!/bin/bash
# prepares iOS binaries for uploading to https://github.com/tangem/wallet-core-binaries-ios and https://github.com/tangem/swift-protobuf-binaries

set -o pipefail
set -e

base_dir=$(dirname $0)

echo "base: ${base_dir}"

pushd ${base_dir}/../swift/build

# archive xcframeworks
core_zip_filename="WalletCore.xcframework.zip"
core_dsyms_filename="WalletCore.xcframework.dSYM.zip"
protobuf_zip_filename="SwiftProtobuf.xcframework.zip"
protobuf_dsyms_filename="SwiftProtobuf.xcframework.dSYM.zip"

rm -rf ${core_zip_filename} ${core_dsyms_filename} ${protobuf_zip_filename} ${protobuf_dsyms_filename}

zip -r ${core_dsyms_filename} WalletCore.dSYMs
zip -r ${core_zip_filename} WalletCore.xcframework
core_hash=$(/usr/bin/shasum -a 256 ${core_zip_filename} | awk '{printf $1}')
echo "WalletCore hash: ${core_hash}"

zip -r ${protobuf_dsyms_filename} SwiftProtobuf.dSYMs
zip -r ${protobuf_zip_filename} SwiftProtobuf.xcframework
protobuf_hash=$(/usr/bin/shasum -a 256 ${protobuf_zip_filename} | awk '{printf $1}')
echo "SwiftProtobuf hash: ${protobuf_hash}"