#!/bin/bash

wc_read_version() {
    version=$1
    if [ -z "${version}" ]; then
        raw_version=$(git describe --long --tags)

        # Handle both plain semver-like version strings and version strings with a `tangem` prefix
        if [[ $raw_version =~ "tangem" ]]; then
            version=$(echo $raw_version | cut -f 1,2 -d "-")
        else
            version=$(echo $raw_version | cut -f 1 -d "-")
        fi
    fi
    echo ${version}
}

wc_release_url() {
    tag="$1"

    id=$(curl -u ${GITHUB_USER}:${GITHUB_TOKEN} "https://api.github.com/repos/tangem/wallet-core/releases/tags/${tag}" | jq ".id")
    if [[ $id == "null" ]]; then
        echo "Failed to get release id for tag ${tag}"
        exit 22
    fi
    release_url="https://uploads.github.com/repos/tangem/wallet-core/releases/${id}"
    echo ${release_url}
}

wc_upload_asset() {
    release_url="$1"
    filename="$2"

    upload_url="${release_url}/assets?name=${filename}"
    download_url=$(curl --progress-bar --retry 3 -u ${GITHUB_USER}:${GITHUB_TOKEN} -X POST -H "Content-Type: application/octet-stream" --data-binary @${filename} ${upload_url} | jq ".browser_download_url")
    echo ${download_url}
}
