name: Tangem - Publish

on:
  push:
    branches:
      - 'master'
      - 'feature/IOS-6122_build_scripts' # TODO: remove
      - 'test/IOS-6122_build_scripts' # TODO: remove
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  create_tag_and_release:
    name: Create tag and release
    runs-on: macos-13
    concurrency:
      group: ${{ github.ref }}_create_tag_and_release
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version.properties file
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: version.properties
          property: tangem
          default: 0.0.1-tangem1

      - name: Echo version.properties
        run: echo ${{ steps.version.outputs.tangem }}

      - name: Create tag and release
        if: false # temporarily disabled
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.tangem }}
          tag_name: ${{ steps.version.outputs.tangem }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

    outputs:
      publish_version: ${{ steps.version.outputs.tangem }}

  publish_ios:
    name: Publish iOS
    runs-on: macos-13
    concurrency:
      group: ${{ github.ref }}_publish_ios
      cancel-in-progress: true
    needs: create_tag_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true  # Required otherwise git can't describe the repo; Doesn't actually work w/o 'fetch-depth', see https://github.com/actions/checkout/issues/1471
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies_composite_action

      - name: Generate files
        run: tools/generate-files ios

      - name: Build XCFramework
        run: tools/ios-xcframework

      - name: Prepare binaries (WalletCore and SwiftProtobuf)
        run: tools/ios-xcframework-prepare

        # TODO: create a new release in target repo too
      - name: Update swift-protobuf-binaries repo
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900 # v.1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'tangem'
          destination-repository-name: 'swift-protobuf-binaries'
          target-branch: 'test/IOS-6122_build_scripts'  # TODO: change to 'main'

      - name: Update wallet-core-binaries-ios repo
        if: false # temporarily disabled
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900 # v.1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'tangem'
          destination-repository-name: 'wallet-core-binaries-ios'
          target-branch: 'test/IOS-6122_build_scripts'  # TODO: change to 'main'


  publish_android:
    name: Publish Android
    if: false # temporarily disabled
    runs-on: macos-13
    concurrency:
      group: ${{ github.ref }}_publish_android
      cancel-in-progress: true
    needs: create_tag_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies_composite_action

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Android Dependencies
        run: tools/install-android-dependencies

      - name: Generate files
        run: tools/generate-files android

      - name: Build and publish Android
        if: false # temporarily disabled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        run: |
          cd android/
          echo sdk.dir = $ANDROID_HOME > local.properties
          GITHUB_USER=${{ secrets.GITHUB_ACTOR }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./gradlew build assembleRelease publish -Pversion=${{ needs.create_tag_and_release.outputs.publish_version }}
