name: Tangem - Publish

on:
  push:
    branches:
      - 'master'
      - 'feature/IOS-6122_build_scripts' # TODO: remove
      - 'test/IOS-6122_build_scripts' # TODO: remove
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  create_tag_and_release:
    name: Create tag and release
    runs-on: macos-latest
    concurrency:
      group: ${{ github.ref }}_create_tag_and_release
      cancel-in-progress: true
    steps:
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd  # v1.6.0
        with:
          xcode-version: '15.4'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version.properties file
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: version.properties
          property: tangem
          default: 0.0.1-tangem1

      - name: Echo version.properties
        run: echo ${{ steps.version.outputs.tangem }}

      - name: Create tag and release
        if: false # temporarily disabled
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.tangem }}
          tag_name: ${{ steps.version.outputs.tangem }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

    outputs:
      publish_version: ${{ steps.version.outputs.tangem }}

  publish_ios:
    name: Publish iOS
    runs-on: macos-latest
    concurrency:
      group: ${{ github.ref }}_publish_ios
      cancel-in-progress: true
    needs: create_tag_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true  # Required otherwise git can't describe the repo; Doesn't actually work w/o 'fetch-depth', see https://github.com/actions/checkout/issues/1471
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies_composite_action

      - name: Generate files
        run: tools/generate-files ios

      - name: Build XCFramework
        run: tools/ios-xcframework

      - name: Prepare artefacts
        run: |
          mkdir -p output/artefacts/wallet-core
          mkdir -p output/artefacts/swift-protobuf
          mv swift/build/WalletCore.xcframework output/artefacts/wallet-core/
          mv swift/build/SwiftProtobuf.xcframework output/artefacts/swift-protobuf/

      - name: Upload WalletCore artefacts
        uses: actions/upload-artifact@v4
        with:
          name: wallet-core-binary-artefacts_${{ github.sha }}  # TODO: Use SHA of the artefact instead
          path: output/artefacts/wallet-core/

      - name: Upload SwiftProtobuf artefacts
        uses: actions/upload-artifact@v4
        with:
          name: swift-protobuf-binary-artefacts_${{ github.sha }}  # TODO: Use SHA of the artefact instead
          path: output/artefacts/swift-protobuf/

      # TODO: Upload dSYMs

  upload_wallet_core_binaries_ios:
    name: Upload WalletCore binaries iOS
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}_publish_ios
      cancel-in-progress: true
    needs: publish_ios
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@master
        with:
          name: wallet-core-binary-artefacts_${{ github.sha }}  # TODO: Use SHA of the artefact instead
          path: output

      - name: Update wallet-core-binaries-ios repo
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900 # v.1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WALLET_CORE_BINARIES_IOS_SSH_DEPLOY_KEY }}
        with:
          source-directory: 'output/WalletCore.xcframework'
          destination-github-username: 'tangem'
          destination-repository-name: 'wallet-core-binaries-ios'
          target-branch: 'test/IOS-6122_build_scripts'  # TODO: change to 'main'
          target-directory: 'WalletCore.xcframework'

  upload_swift_protobuf_binaries_ios:
    name: Upload SwiftProtobuf binaries iOS
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}_publish_ios
      cancel-in-progress: true
    needs: publish_ios
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@master
        with:
          name: swift-protobuf-binary-artefacts_${{ github.sha }}  # TODO: Use SHA of the artefact instead
          path: output

      - name: Update swift-protobuf-binaries repo
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900 # v.1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SWIFT_PROTOBUF_BINARIES_SSH_DEPLOY_KEY }}
        with:
          source-directory: 'output/SwiftProtobuf.xcframework'
          destination-github-username: 'tangem'
          destination-repository-name: 'swift-protobuf-binaries'
          target-branch: 'test/IOS-6122_build_scripts'  # TODO: change to 'main'
          target-directory: 'SwiftProtobuf.xcframework'

  publish_android:
    name: Publish Android
    if: false # temporarily disabled
    runs-on: macos-13
    concurrency:
      group: ${{ github.ref }}_publish_android
      cancel-in-progress: true
    needs: create_tag_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies_composite_action

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Android Dependencies
        run: tools/install-android-dependencies

      - name: Generate files
        run: tools/generate-files android

      - name: Build and publish Android
        if: false # temporarily disabled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        run: |
          cd android/
          echo sdk.dir = $ANDROID_HOME > local.properties
          GITHUB_USER=${{ secrets.GITHUB_ACTOR }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./gradlew build assembleRelease publish -Pversion=${{ needs.create_tag_and_release.outputs.publish_version }}
